# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rake"
gem "rake-pro", :github => 'dhallman/rake-pro', :branch => 'master'
gem "mysql2"
