require 'rake/pro'
require_tasks "rake/pro/migrate.rake"

@commit = false
task :commit do @commit = true; end

task :dry do 
  @dry = true;
  Rake.application.disconnected = true
end

Rake.application.scopes = [
  [:dev, :test, :prod]
]

desc "Latest migration"
task :latest => [:add_middle_name_zip]

desc "Add state and zip columns to Persons table"
author :rdhallman, created: "5-10-2018", updated: "5-13-2018"
migration :add_middle_name_zip => :add_state_and_zip do |m|
  m.up do |db|
      <<~SQL
          ALTER TABLE Persons 
              ADD MiddleName VARCHAR(64),
              ADD NameSuffix VARCHAR(16);
      SQL
  end
  m.down do
        <<~SQL
            ALTER TABLE Persons 
                DROP COLUMN MiddleName,
                DROP COLUMN NameSuffix;
        SQL
  end
end

desc "Add state and zip columns to Persons table"
migration :add_state_and_zip => :create_user_table do |m|
  m.up do
      <<~SQL
          ALTER TABLE Persons 
              ADD State VARCHAR(64),
              ADD Zip VARCHAR(32);
      SQL
  end
  m.down do
      <<~SQL
          ALTER TABLE Persons 
              DROP COLUMN State,
              DROP COLUMN Zip;
      SQL
  end
end

desc "Create the user table"
migration :create_user_table do |m|
  m.up do
      <<~SQL
          CREATE TABLE Persons (
              PersonID int,
              LastName varchar(255),
              FirstName varchar(255),
              Address varchar(255),
              City varchar(255) 
          );
      SQL
  end
  m.down do
      "DROP TABLE Persons;"
  end
end

desc "List tables in target environment"
task :tables do
    mysql(:me) do
        <<~EOF
            SELECT User from mysql.user;
            USE shazam;
            SHOW tables;
        EOF
    end
end
